const images = {
    email: '/assets/email.png',
    mobile: '/assets/mobile.png',
    api: '/assets/api.png',
    cpp: '/assets/cpp.png',
    css: '/assets/css.png',
    figma: '/assets/figma.png',
    flutter: '/assets/flutter.png',
    git: '/assets/git.png',
    graphql: '/assets/graphql.png',
    html: '/assets/html.png',
    javascript: '/assets/javascript.png',
    mu5: '/assets/mu5.png',
    node: '/assets/node.png',
    python: '/assets/python.png',
    react: '/assets/react.png',
    redux: '/assets/redux.png',
    sass: '/assets/sass.png',
    typescript: '/assets/typescript.png',
    vue: '/assets/vue.png',
    tailwind: '/assets/tailwind.png',
    linkedin: '/assets/linkedin.png',
    profile: '/assets/profile.png',
    circle: '/assets/circle.svg',
    logo: '/assets/logo.png',
    adidas: '/assets/adidas.png',
    amazon: '/assets/amazon.png',
    asus: '/assets/asus.png',
    bolt: '/assets/bolt.png',
    nb: '/assets/nb.png',
};

export default images;
